# Site settings
title: Life of Coder
header-img: img/home-bg.png
email: rathind14@gmail.com
copyright_name: rathi2016
description: > # this means to ignore newlines until "baseurl:"
  Be curious to learn new in language  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  rathi2016
learn_profile: rathi2016
email_username: rathind14@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
